import styled from 'styled-components';

export const StyledLoader = styled.div`
  @keyframes ldio-bluzbsuruld {
    0% {
      transform: rotate(0deg);
    }
    50% {
      transform: rotate(180deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }
  .ldio-bluzbsuruld div {
    position: absolute;
    animation: ldio-bluzbsuruld 1s linear infinite;
    width: 160px;
    height: 160px;
    top: 20px;
    left: 20px;
    border-radius: 50%;
    box-shadow: 0 4px 0 0 #5f16e9;
    transform-origin: 80px 82px;
  }
  .loadingio-spinner-eclipse-6snw0tie2ow {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-bluzbsuruld {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-bluzbsuruld div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
`;
