/* eslint-disable @typescript-eslint/no-unused-vars */
export const Nationalities = [
  ['0', 'Antiguano'],
  ['1', 'Argentino'],
  ['2', 'Bahamense'],
  ['3', 'Barbadiano, barbadense'],
  ['4', 'Belizenho'],
  ['5', 'Boliviano'],
  ['6', 'Brasileiro'],
  ['7', 'Chileno'],
  ['8', 'Colombiano'],
  ['9', 'Costarriquenho'],
  ['10', 'Cubano'],
  ['11', 'Dominicano'],
  ['12', 'Equatoriano'],
  ['13', 'Salvadorenho'],
  ['14', 'Granadino'],
  ['15', 'Guatemalteco'],
  ['16', 'Guianês'],
  ['17', 'Guianense'],
  ['18', 'Haitiano'],
  ['19', 'Hondurenho'],
  ['20', 'Jamaicano'],
  ['21', 'Mexicano'],
  ['22', 'Nicaraguense'],
  ['23', 'Panamenho'],
  ['24', 'Paraguaio'],
  ['25', 'Peruano'],
  ['26', 'Portorriquenho'],
  ['27', 'Dominicana'],
  ['28', 'São-cristovense'],
  ['29', 'São-vicentino'],
  ['30', 'Santa-lucense'],
  ['31', 'Surinamês'],
  ['32', 'Trindadense'],
  ['33', 'Uruguaio'],
  ['34', 'Venezuelano'],
  ['35', 'Alemão'],
  ['36', 'Austríaco'],
  ['37', 'Belga'],
  ['38', 'Croata'],
  ['39', 'Dinamarquês'],
  ['40', 'Eslovaco'],
  ['41', 'Esloveno'],
  ['42', 'Espanhol'],
  ['43', 'Francês'],
  ['44', 'Grego'],
  ['45', 'Húngaro'],
  ['46', 'Irlandês'],
  ['47', 'Italiano'],
  ['48', 'Noruego'],
  ['49', 'Holandês'],
  ['50', 'Polonês'],
  ['51', 'Português'],
  ['52', 'Britânico'],
  ['53', 'Inglês'],
  ['54', 'Galês'],
  ['55', 'Escocês'],
  ['56', 'Romeno'],
  ['57', 'Russo'],
  ['58', 'Sérvio'],
  ['59', 'Sueco'],
  ['60', 'Suíço'],
  ['61', 'Turco'],
  ['62', 'Ucraniano'],
  ['63', 'Americano'],
  ['64', 'Canadense'],
  ['65', 'Angolano'],
  ['66', 'Moçambicano'],
  ['67', 'Sul-africano'],
  ['68', 'Zimbabuense'],
  ['69', 'Argélia'],
  ['70', 'Comorense'],
  ['71', 'Egípcio'],
  ['72', 'Líbio'],
  ['73', 'Marroquino'],
  ['74', 'Ganés'],
  ['75', 'Queniano'],
  ['76', 'Ruandês'],
  ['77', 'Ugandense'],
  ['78', 'Bechuano'],
  ['79', 'Marfinense'],
  ['80', 'Camaronense'],
  ['81', 'Nigeriano'],
  ['82', 'Somali'],
  ['83', 'Australiano'],
  ['84', 'Neozelandês'],
  ['85', 'Afegão'],
  ['86', 'Saudita'],
  ['87', 'Armeno'],
  ['88', 'Bangladesh'],
  ['89', 'Chinês'],
  ['90', 'Norte-coreano, coreano'],
  ['91', 'Sul-coreano, coreano'],
  ['92', 'Indiano'],
  ['93', 'Indonésio'],
  ['94', 'Iraquiano'],
  ['95', 'Iraniano'],
  ['96', 'Israelita'],
  ['97', 'Japonês'],
  ['98', 'Malaio'],
  ['99', 'Nepalês'],
  ['100', 'Omanense'],
  ['101', 'Paquistanês'],
  ['102', 'Palestino'],
  ['103', 'Qatarense'],
  ['104', 'Sírio'],
  ['105', 'Cingalês'],
  ['106', 'Tailandês'],
  ['107', 'Timorense, maubere'],
  ['108', 'Árabe, emiratense'],
  ['109', 'Vietnamita'],
  ['110', 'Iemenita'],
];

const old = [
  ['Antígua e Barbuda', 'Antiguano'],
  ['Argentina', 'Argentino'],
  ['Bahamas', 'Bahamense'],
  ['Barbados', 'Barbadiano, barbadense'],
  ['Belize', 'Belizenho'],
  ['Bolívia', 'Boliviano'],
  ['Brasil', 'Brasileiro'],
  ['Chile', 'Chileno'],
  ['Colômbia', 'Colombiano'],
  ['Costa Rica', 'Costarriquenho'],
  ['Cuba', 'Cubano'],
  ['Dominica', 'Dominicano'],
  ['Equador', 'Equatoriano'],
  ['El Salvador', 'Salvadorenho'],
  ['Granada', 'Granadino'],
  ['Guatemala', 'Guatemalteco'],
  ['Guiana', 'Guianês'],
  ['Guiana Francesa', 'Guianense'],
  ['Haiti', 'Haitiano'],
  ['Honduras', 'Hondurenho'],
  ['Jamaica', 'Jamaicano'],
  ['México', 'Mexicano'],
  ['Nicarágua', 'Nicaraguense'],
  ['Panamá', 'Panamenho'],
  ['Paraguai', 'Paraguaio'],
  ['Peru', 'Peruano'],
  ['Porto Rico', 'Portorriquenho'],
  ['República Dominicana', 'Dominicana'],
  ['São Cristóvão e Nevis', 'São-cristovense'],
  ['São Vicente e Granadinas', 'São-vicentino'],
  ['Santa Lúcia', 'Santa-lucense'],
  ['Suriname', 'Surinamês'],
  ['Trinidad e Tobago', 'Trindadense'],
  ['Uruguai', 'Uruguaio'],
  ['Venezuela', 'Venezuelano'],
  ['Alemanha', 'Alemão'],
  ['Áustria', 'Austríaco'],
  ['Bélgica', 'Belga'],
  ['Croácia', 'Croata'],
  ['Dinamarca', 'Dinamarquês'],
  ['Eslováquia', 'Eslovaco'],
  ['Eslovênia', 'Esloveno'],
  ['Espanha', 'Espanhol'],
  ['França', 'Francês'],
  ['Grécia', 'Grego'],
  ['Hungria', 'Húngaro'],
  ['Irlanda', 'Irlandês'],
  ['Itália', 'Italiano'],
  ['Noruega', 'Noruego'],
  ['Países Baixos', 'Holandês'],
  ['Polônia', 'Polonês'],
  ['Portugal', 'Português'],
  ['Reino Unido', 'Britânico'],
  ['Inglaterra', 'Inglês'],
  ['País de Gales', 'Galês'],
  ['Escócia', 'Escocês'],
  ['Romênia', 'Romeno'],
  ['Rússia', 'Russo'],
  ['Sérvio', 'Sérvio'],
  ['Suécia', 'Sueco'],
  ['Suíça', 'Suíço'],
  ['Turquia', 'Turco'],
  ['Ucrânia', 'Ucraniano'],
  ['Estados Unidos', 'Americano'],
  ['Canadá', 'Canadense'],
  ['Angola', 'Angolano'],
  ['Moçambique', 'Moçambicano'],
  ['África do Sul', 'Sul-africano'],
  ['Zimbabue', 'Zimbabuense'],
  ['Argélia', 'Argélia'],
  ['Comores', 'Comorense'],
  ['Egito', 'Egípcio'],
  ['Líbia', 'Líbio'],
  ['Marrocos', 'Marroquino'],
  ['Gana', 'Ganés'],
  ['Quênia', 'Queniano'],
  ['Ruanda', 'Ruandês'],
  ['Uganda', 'Ugandense'],
  ['Botsuana', 'Bechuano'],
  ['Costa do Marfim', 'Marfinense'],
  ['Camarões', 'Camaronense'],
  ['Nigéria', 'Nigeriano'],
  ['Somália', 'Somali'],
  ['Austrália', 'Australiano'],
  ['Nova Zelândia', 'Neozelandês'],
  ['Afeganistão', 'Afegão'],
  ['Arábia Saudita', 'Saudita'],
  ['Armênia', 'Armeno'],
  ['Armeno', 'Bangladesh'],
  ['China', 'Chinês'],
  ['Coréia do Norte', 'Norte-coreano, coreano'],
  ['Coréia do Sul', 'Sul-coreano, coreano'],
  ['Índia', 'Indiano'],
  ['Indonésia', 'Indonésio'],
  ['Iraque', 'Iraquiano'],
  ['Irã', 'Iraniano'],
  ['Israel', 'Israelita'],
  ['Japão', 'Japonês'],
  ['Malásia', 'Malaio'],
  ['Nepal', 'Nepalês'],
  ['Omã', 'Omanense'],
  ['Paquistão', 'Paquistanês'],
  ['Palestina', 'Palestino'],
  ['Qatar', 'Qatarense'],
  ['Síria', 'Sírio'],
  ['Sri Lanka', 'Cingalês'],
  ['Tailândia', 'Tailandês'],
  ['Timor-Leste', 'Timorense, maubere'],
  ['Emirados Árabes Unidos', 'Árabe, emiratense'],
  ['Vietnã', 'Vietnamita'],
  ['Iêmen', 'Iemenita'],
];
